<div class="row">
    <div class="col-md-4">&nbsp;</div>
        <div class="col-md-4">
            <h2>COTIZA TU RED</h2>
            <form>
                <div class="form-group">
                    <label for="inputEmail1">e-mail</label>
                    <input type="email" class="form-control" id="Email" placeholder="e-mail">
                </div>
                <div class="form-group">
                    <label for="Empresa">Nombre / Empresa</label>
                    <input type="text" class="form-control" id="Nombre" placeholder="Ingrese un nombre">
                </div>                
                <div class="form-group">
                    <label for="InputPaginas">Número de puntos de red</label>
                    <input type="text" class="form-control" id="noPaginas" placeholder="Ingrese un número">
                </div>
                <div class="checkbox">
                    <label>
                      <input type="checkbox"> Con router
                    </label>
                </div>
                <div class="form-group">
                    <label for="Empresa">Categoria de cableado</label>
                </div>                
                <div class="radio">
                    <label>
                        <input type="radio" value="option1" name="tipoCable" checked> Cat 5
                    </label>
                </div>
                <div class="radio">
                    <label>
                      <input type="radio" name="tipoCable"> Cat 6
                    </label>
                </div>     
                <div class="radio">
                    <label>
                      <input type="radio" name="tipoCable"> Otros
                    </label>
                </div>                                  
                
                <button type="submit" class="btn btn-primary">Cotizar</button>   
                
                <div class="delimitador">
                    <img class="centrado"  src="img/red.jpg"  />
                </div>
            </form>            
        </div>
    <div class="col-md-4">&nbsp;</div>
</div>

