<div class="row">
    <div class="col-md-4 col-lg-4">&nbsp;</div>
        <div class="col-md-4 col-lg-4">
            <h2>Cotizar instalación de red</h2>
            <?php if(isset($this->msg)){echo $this->msg;}?>
            <form action="<?php echo BASE_URL.'cotizared/cotizar'; ?>" method="post">
                <div class="form-group">
                    <label for="inputEmail1">e-mail</label>
                    <input type="email" class="form-control" name="Email" placeholder="e-mail">
                </div>
                <div class="form-group">
                    <label for="Empresa">Nombre / Empresa</label>
                    <input type="text" class="form-control" name="Nombre" placeholder="Ingrese un nombre">
                </div>                
                <div class="form-group">
                    <label for="InputPaginas">Número de puntos de red</label>
                    <input type="text" class="form-control" name="noPuntos" placeholder="Ingrese un número">
                </div>
                <div class="checkbox">
                    <label>
                      <input type="checkbox" name="router" value="1"> Con router
                    </label>
                </div>
                <div class="form-group">
                    <label for="Empresa">Categoria de cableado</label>
                </div>                
                <div class="radio">
                    <label>
                        <input type="radio" value="op1" name="tipoCable" checked> Cat 5
                    </label>
                </div>
                <div class="radio">
                    <label>
                      <input type="radio" value="op2" name="tipoCable"> Cat 6
                    </label>
                </div>     
                <div class="radio">
                    <label>
                      <input type="radio" value="op3" name="tipoCable"> Otros
                    </label>
                </div>                                  
                
                <button type="submit" class="btn btn-primary">Cotizar</button>   
                
                <div class="delimitador">
                    <img class="centrado"  src="<?php echo BASE_URL; ?>img/red.jpg"  />
                </div>
            </form>             
        </div>
    <div class="col-md-4 col-lg-4">&nbsp;</div>
</div>

