<div class="row">
    <div class="col-md-3 col-lg-3">
        <?php include_once ROOT .'views' . DS . 'layout' . DS . DEFAULT_LAYOUT . DS . 'left_column.php'; ?>
    </div>
    <div class="col-md-6 col-lg-6">
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <div class="col-md-9 col-lg-9">
                    
                    <h2>Modulo de contabilidad</h2>
                    <?php if(isset($this->contenido)){echo $this->contenido;}?>  
                    
                </div>
                <div class="col-md-3 col-lg-3">&nbsp;</div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-6">
                <h3>Solicitar cotización del modulo: Contabilidad</h3>
                <?php if(isset($this->msg)){echo $this->msg;}?>
                <form action="<?php echo BASE_URL.'erp/cotizar/contabilidad'; ?>" method="post" id="formCotizar">
                    <div class="form-group">
                        <label for="inputEmail">e-mail</label>
                        <input type="email" class="form-control" name="Email" placeholder="e-mail">
                    </div>
                    <div class="form-group">
                        <label for="Empresa">Nombre / Empresa</label>
                        <input type="text" class="form-control" name="Nombre" placeholder="Ingrese un nombre">
                    </div>
                    <div class="form-group">
                        <label for="InputTel">Teléfono</label>
                        <input type="text" class="form-control" name="Telefono" placeholder="Ingrese su teléfono">
                    </div>
                    <div class="form-group">
                        <label for="InputDir">Dirección</label>
                        <input type="text" class="form-control" name="Direccion" placeholder="Ingrese su dirección">
                    </div>             
                    <div class="g-recaptcha" data-sitekey="6LcOTgwTAAAAANzXJ8XcyGl05oEQ5A7xv1Go6T4Z"></div>
                    <button onclick="validarDatos();" class="btn btn-primary">Cotizar</button>
                </form>    
            </div>
            <div class="col-md-6 col-lg-6">&nbsp;</div>
        </div>        
    </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>
<script>
    function validarDatos(){
        $("#formCotizar").validate({
                rules: {
                        Email: { required:true, email: true},
                        Nombre: { required: true},                           
                        Telefono: { required:true, number:true},
                        Direccion: { required:true}                         
                },
                messages: {
                        Email: "Este campo debe tener formato de correo y es necesario.",
                        Nombre : "El campo nombre es necesario",                          
                        Telefono : "Este campo debe tener formato numérico y es necesario.",
                        Direccion : "El campo dirección es necesario",                        
                }
        });
        if($("#formCotizar").valid())
        { 
            $('#formCotizar').submit();
        }       
    }
</script>

