<div class="row">
    <div class="col-md-3 col-lg-3">&nbsp;</div>
        <div class="col-md-6 col-lg-6">
            <h2>ERP SGF de SSISA</h2>
            
            <h4>¿Por qué utilizar el ERP SGF de SSISA?</h4>
            <p>
                ERP SGF de SSISA es una herramientas ERP alternativa a los sistemas de gestión comercial tradicionales como JEDWARDS,
                SALESFORCE, MICROSOFT DYNAMICS, SAP...”
            </p>
            <p>Nuestra solución cuenta con los siguientes módulos:</p>
            <ol>
                <li>Contabilidad, el sistema ya cuenta con una propuesta de catálogo contable que puede utilizar su empresa,</li>
                <li>Bancos (generación de cheques y pagos, multimoneda, conciliación bancaria, ..)</li>
                <li>Cuentas por pagar&nbsp; (compras locales e importaciones, libro de compras-iva crédito, pedido, orden de compra, orden de pago, interfaz con inventarios, reportes, …),</li>
                <li>Cuentas por cobrar (cotización, facturación, exportaciones, libro de ventas-iva débito, interfaz con inventarios, …),</li>
                <li>Inventarios (multibodega, multiproducto, marca, producto, reportes)</li>
                <li>Recursos Humanos, integrado con Planilla,</li>
                <li>Planilla (ingresos y egresos en forma parametrizada, interfaz con bancos, …),</li>
                <li>Activos Fijos,</li>
                <li>Todos los módulos tienen: consultas, reportes, interfaz con la contabilidad y entre ellos mismos.</li>
                <li>Seguridad y roles, a nivel de aplicación, usuarios y empresas.</li>
            </ol>            
            <p>
                Desarrollado en Jdeveloper con base de datos ORACLE, puede instalarse en la nube con sistema operativo Windows o Linux, 
                con Weblogic o Glassfish, se pueden utilizar las versiones gratuitas de Base de datos Oracle, Glassfish y Linux.
            </p>
            <p>Como parte del valor agregado del software ERP SGF de SSISA, se brinda lo siguiente:</p>
            <ul>
                <li>Garantía,</li>
                <li>Documentación del usuario final y técnica,</li>
                <li>Capacitación,</li>
                <li>Instalación y configuración inicial,</li>
                <li>Soporte y</li>
                <li>Outsourcing de personal en la implementación o fase de producción.</li>
            </ul>
            <p><?php print_r($this->posts); ?></p>
        </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>

