<div class="row">
    <div class="col-md-4">&nbsp;</div>
        <div class="col-md-4">
            <h2>ERP</h2>
            <ol style="margin-left: 40px;">
                <li>Contabilidad, el sistema ya cuenta con una propuesta de catálogo contable que puede utilizar su empresa,</li>
                <li>Bancos (generación de cheques y pagos, multimoneda, conciliación bancaria, ..)</li>
                <li>Cuentas por pagar&nbsp; (compras locales e importaciones, libro de compras-iva crédito, pedido, orden de compra, orden de pago, interfaz con inventarios, reportes, …),</li>
                <li>Cuentas por cobrar (cotización, facturación, exportaciones, libro de ventas-iva débito, interfaz con inventarios, …),</li>
                <li>Inventarios (multibodega, multiproducto, marca, producto, reportes)</li>
                <li>Recursos Humanos, integrado con Planilla,</li>
                <li>Planilla (ingresos y egresos en forma parametrizada, interfaz con bancos, …),</li>
                <li>Activos Fijos,</li>
                <li>Todos los módulos tienen: consultas, reportes, interfaz con la contabilidad y entre ellos mismos.</li>
                <li>Seguridad y roles, a nivel de aplicación, usuarios y empresas.</li>
            </ol>            
            <p><?php print_r($this->posts); ?></p>
        </div>
    <div class="col-md-4">&nbsp;</div>
</div>

