    <div class="row">
        <div class="col-lg-12">
            <script type='text/javascript' src='http://maps.google.com/maps/api/js?sensor=false&callback=init'></script>        
            <script type="text/javascript">
                var map;
                function init() {
                    var mapOptions = {
                        zoom: 15,
                        center:new google.maps.LatLng(14.61082, -90.526574),
                        mapTypeId: google.maps.MapTypeId.ROADMAP
                    }
                    map = new google.maps.Map(document.getElementById("mapa"),mapOptions);
                }        
            </script>
            <div id="mapa" style="width: 300px; height: 300px;">

            </div>                                     
        </div>   
    </div>    
    <div class="row">
        <div class="col-md-6">                                  
            <h1>LOGO</h1>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-10">
                    <form method="post" id="mensajeForm" action="./?action=send_mess">                                        
                        <div class="form-group">
                        <div class="form-group">
                            <label class="control-label">Nombre:</label>
                            <input required="required" name="nombre" id="nombre" type="text" class="form-control inputT" ng-model="nuevoMensaje.correo"/>
                        </div>										
                            <label class="control-label">Correo:</label>
                            <input required="required" name="correo" id="correo" type="text" class="form-control inputT" ng-model="nuevoMensaje.correo"/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Asunto:</label>
                            <input required="required" name="asunto" id="asunto" type="text" class="form-control inputT" ng-model="nuevoMensaje.correo"/>
                        </div>										
                        <div class="form-group">
                            <label class="control-label">Mensaje:</label>
                            <textarea required="required" class="form-control" name="msg" id="texto" rows="5" placeholder="Contáctanos, escribe aquí tu mensaje."></textarea>
                        </div>
                        <div class="g-recaptcha" data-sitekey="6LcOTgwTAAAAANzXJ8XcyGl05oEQ5A7xv1Go6T4Z"></div>
                        <p id="info">Gracias por contactarnos. Pronto nos estaremos comunicando contigo.</p>
                        <button class="btn btn-primary"  type="submit">Enviar</button>
                    </form>
                </div>
                <div class="col-md-2"  ></div>
            </div>
        </div>
    </div>
