<div class="row">
    <div class="col-lg-12">
        <script type='text/javascript' src='http://maps.google.com/maps/api/js?sensor=false&callback=init'></script>        
        <script type="text/javascript">
            var map;
            function init() {
                var mapOptions = {
                    zoom: 15,
                    center:new google.maps.LatLng(14.61082, -90.526574),
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                }
                map = new google.maps.Map(document.getElementById("mapa"),mapOptions);
            }        
        </script>
        <div style="width: 800px; height: 20px; margin: 10px auto;">          
            <h3>Dirección: 5a. Calle 1-62, zona 9 Guatemala, Guatemala</h3>
        </div>         
        <div id="mapa" style="width: 800px; height: 300px; margin: 0 auto;">
            
        </div>   
    </div>   
</div>  
<div class="row">
    <div class="col-md-3 col-lg-3">&nbsp;</div>
    <div class="col-md-6 col-lg-6">
        <div class="row">
            <div class="col-md-6 col-lg-6">
                <h2>Contáctanos</h2>
                <?php if(isset($this->msg)){echo $this->msg;}?>                
                <form action="<?php echo BASE_URL.'contacto/contactar'; ?>" method="post" id="formCotizar">
                    <div class="form-group">
                        <label for="inputEmail">e-mail</label>
                        <input type="email" class="form-control" name="Email" placeholder="e-mail">
                    </div>
                    <div class="form-group">
                        <label for="Empresa">Nombre / Empresa</label>
                        <input type="text" class="form-control" name="Nombre" placeholder="Ingrese un nombre">
                    </div>
                    <div class="form-group">
                        <label for="InputTel">Teléfono</label>
                        <input type="text" class="form-control" name="Telefono" placeholder="Ingrese su teléfono">
                    </div>
                    <div class="form-group">
                        <label for="InputDir">Dirección</label>
                        <input type="text" class="form-control" name="Direccion" placeholder="Ingrese su dirección">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Mensaje:</label>
                        <textarea required="required" class="form-control" name="msg" rows="5" placeholder="Contáctanos, escribe aquí tu mensaje."></textarea>
                    </div>                    
                    <div class="g-recaptcha" data-sitekey="6LcOTgwTAAAAANzXJ8XcyGl05oEQ5A7xv1Go6T4Z"></div>
                    <button onclick="validarDatos();" class="btn btn-primary">Enviar</button> 
                </form>  
            </div>
            <div class="col-md-6 col-lg-6">&nbsp;</div>
        </div>          
    </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>    
<script>
    function validarDatos(){
        $("#formCotizar").validate({
                rules: {
                        Email: { required:true, email: true},
                        Nombre: { required: true},                           
                        Telefono: { required:true, number:true},
                        Direccion: { required:true},
                        msg: { required:true}                         
                },
                messages: {
                        Email: "Este campo debe tener formato de correo y es necesario.",
                        Nombre : "El campo nombre es necesario",                          
                        Telefono : "Este campo debe tener formato numérico y es necesario.",
                        Direccion : "El campo dirección es necesario",
                        msg : "El campo mensaje es necesario",                        
                }
        });
        if($("#formCotizar").valid())
        { 
            $('#formCotizar').submit();
        }       
    }
</script>
