    <!--div class="row">  
        <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
            <h2>SSISA</h2>                       
        </div>                                   
    </div-->
    <div class="row">
            <div class="col-md-3 centrado">
                <div class="list-group">
                    <a href="#" class="list-group-item active">
                        Referencias de clientes:
                    </a>
                    <a href="#" class="list-group-item">                      
                        <h4>Ing. Edgar Castro:</h4>
                        <h5>Proyectos:</h5>
                        <ul> 
                            <li>Banco de la República</li>
                            <li>BellSouth</li>                            
                            <li>Telefónica de Guatemala</li> 
                            <li>Telefónica de El Salvador</li>                            
                            <li>El Renap</li>
                        </ul>                
                        <p>Cel. (502) 4212-2925
                        Proyectos: Outsourcing de Personal y Desarrollo de software</p>
                    </a>
                    <a href="#" class="list-group-item">                       
                        <h4>Ing. Jorge Gómez</h4>
                        <p>Director de Informática<br>
                        Universidad de San Carlos de Guatemala<br>
                        Cel. (502) 5951-6693<br>
                        Proyecto: Desarrollo de software para la planilla de la USAC, en Jdeveloper
                        Con Oracle, y ambiente web</p>
                    </a>
                    <a href="#" class="list-group-item">                       
                        <h4>Ing. Byron Cifuentes</h4>
                        <p>Jefe de Producción Post Pago<br> 
                        Telefónica de Guatemala<br>
                        Cel. (502) 5401-0907<br>
                        Proyecto: Outsourcing de Personal</p>
                    </a>
                </div>
            </div>
<div class="col-md-9"> 
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div id="slider" style="margin:0px auto;">
                    <img src="img/red_virtual.jpg" alt="" data-transition='{"effect": "cubeUp", "slices": 9, "animSpeed": 1200, "delay": 100, "delayDir": "fromCentre", "easing": "easeInOutBack", "depthOffset": 300, "sliceGap": 30}' />
                    <img src="img/outsourcing.jpg" alt=""  data-transition='{"effect": "cubeRight", "slices": 5, "delay": 200}' />
                    <img src="img/desarrollo_web.jpg" alt=""  data-transition='{"effect": "cubeDown", "slices": 15, "animSpeed": 3000, "delay": 30, "easing": "easeInOutElastic", "depthOffset": 200, "sliceGap": 20}' />
                    <img src="img/servidores.jpg" alt="" data-transition='{"effect": "cubeLeft", "slices": 5, "delay": 200, "delayDir": "toCentre"}' />
                    <img src="img/erp.jpg" alt="" data-transition='{"effect": "cubeUp", "slices": 5, "animSpeed": 1300, "delay": 100, "easing": "easeInOutCubic", "depthOffset": 500, "sliceGap": 50}' />
                    <!--img src="img/deus-ex2.jpg" alt="" data-transition='{"effect": "cubeRight", "slices": 5, "delay": 200, "delayDir": "last-first"}' /-->
            </div>
            
            <script>!window.jQuery && document.write('<script src="js/jquery-1.9.1.min.js"><\/script>')</script>
            <script src="js/jquery-migrate-1.1.1.min.js"></script>
            <script src="js/jquery.ccslider-3.0.2.min.js"></script>
            <script>
                    $(function(){
                            $('#demo-nav').find('a').tooltip({effect: 'slide'});
                    });

                    $(window).load(function(){
                            $('#slider').ccslider({
                                    _3dOptions: {
                                            imageWidth: 900,
                                            imageHeight: 350
                                    }
                            });
                    });
            </script>             
        </div>    
    </div>
    <div class="row">
            <div class="col-md-4">
		<section>
                    <div class="cards">
                        <div class="card">
                            <div class="box" >
                                <div class="blue-text">
                                    <h3>Solución ERP </h3>
                                    <ul>
                                        <li>
                                            Contabilidad
                                        </li>
                                        <li>
                                            Bancos
                                        </li>
                                        <li>
                                            Cuentas por cobrar
                                        </li>
                                        <li>
                                            Cuentas por pagar
                                        </li>    
                                        <li>
                                            Inventarios
                                        </li> 
                                        <li>
                                            Activos fijos
                                        </li> 
                                        <li>
                                            Recursos humanos
                                        </li> 
                                        <li>
                                            Punto de venta 
                                        </li>                                        
                                    </ul>
                                    <p>Información técnica: Nuestra aplicación funciona con un servidor glasfish o web logic, y con una base de datos oracle express o superiores.</p>                                    
                                </div>
                                
                            </div>
                        </div>
                    </div>
		</section>  
            </div>
            <div class="col-md-4">
		<section>                 
                    <div class="cards">
                        <div class="card dark">
                            <div class="box" >
                                <div class="blue-text">
                                    <h1>Renta y Venta</h1>                                       
                                    <h3>Equipos y Suministros</h3>
                                    <div class="delimitador">                                 
                                        <img src="<?php echo BASE_URL; ?>img/renta-equipo.jpg"  />
                                    </div>                                            
                                </div>
                                <p>Ideal para proyectos, conferencias, eventos, PYMES y multinacionales.</p>
                            </div>
                        </div>
                    </div> 
		</section>                     
            </div>
            <div class="col-md-4">
		<section>                 
                    <div class="cards">
                        <div class="card dark">
                            <div class="box" >
                                <div class="blue-text">
                                    <h3>Outsourcing</h3>                                       
                                    <h1>Personal IT</h1>
                                    <div class="delimitador">
                                        <img src="<?php echo BASE_URL; ?>img/solucion-rrhh.jpg"  />
                                    </div>                                            
                                </div>
                                <p>Ideal para proyectos informáticos, IN-HOUSE, call center, BPOs.</p>
                            </div>
                        </div>
                    </div> 
		</section>                		
            </div>
    </div>
</div>    
    </div>
    <!--div class="row">  
        <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
            <table class="table table-bordered table-hover table-striped">
                <tr ng-repeat="nombreDeObjeto in miVector">
                    <td>{{nombreDeObjeto.name}}</td>
                    <td>{{nombreDeObjeto.snippet}}</td>
                </tr>
            </table>
        </div>                                   
    </div-->    


