    <!--div class="row">  
        <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
            <h2>SSISA</h2>                       
        </div>                                   
    </div-->
    <div class="row">
        <div class="col-md-2 col-lg-2 hidden-sm hidden-xs">
            <img class="img-lg" src="<?php echo BASE_URL; ?>img/ssisa_logo.png"  />
        </div>
        <div class="col-xs-12 col-sm-12  visible-xs visible-sm">
            <img class="img-md" src="<?php echo BASE_URL; ?>img/ssisa_logo.png"  />
        </div>                  
        <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            <div id="slider" style="margin:0px auto; z-index: 0 !important;">
                    <!--img src="img/red_virtual.jpg" alt="" data-transition='{"effect": "cubeUp", "slices": 9, "animSpeed": 1200, "delay": 100, "delayDir": "fromCentre", "easing": "easeInOutBack", "depthOffset": 300, "sliceGap": 30}' /-->
                    <img src="img/outsourcing.jpg" alt=""  data-transition='{"effect": "cubeRight", "slices": 5, "delay": 200}' />
                    <img src="img/desarrollo_web.jpg" alt=""  data-transition='{"effect": "cubeDown", "slices": 15, "animSpeed": 3000, "delay": 30, "easing": "easeInOutElastic", "depthOffset": 200, "sliceGap": 20}' />
                    <img src="img/servidores.jpg" alt="" data-transition='{"effect": "cubeLeft", "slices": 5, "delay": 200, "delayDir": "toCentre"}' />
                    <img src="img/erp.jpg" alt="" data-transition='{"effect": "cubeUp", "slices": 5, "animSpeed": 1300, "delay": 100, "easing": "easeInOutCubic", "depthOffset": 500, "sliceGap": 50}' />
                    <!--img src="img/deus-ex2.jpg" alt="" data-transition='{"effect": "cubeRight", "slices": 5, "delay": 200, "delayDir": "last-first"}' /-->
            </div>
            
            <script>!window.jQuery && document.write('<script src="js/jquery-1.9.1.min.js"><\/script>')</script>
            <script src="js/jquery-migrate-1.1.1.min.js"></script>
            <script src="js/jquery.ccslider-3.0.2.min.js"></script>
            <script>
                    $(function(){
                            $('#demo-nav').find('a').tooltip({effect: 'slide'});
                    });

                    $(window).load(function(){
                            $('#slider').ccslider({
                                    _3dOptions: {
                                            imageWidth: 900,
                                            imageHeight: 350
                                    }
                            });
                    });
            </script>             
        </div>    
        <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">&nbsp;</div>         
    </div>       
    <div class="row">
        <div class="col-md-1">&nbsp;</div>
        <div class="col-md-10"> 
            <div class="row">
                <div class="col-md-4">
                    <section>
                        <div class="cards">
                            <div class="card">
                                <div class="box" >
                                    <div class="blue-text">
                                        <h3>Solución ERP </h3>
                                        <ul>
                                            <li>
                                                <a href="<?php echo BASE_URL.'erp/cargarContenido/contabilidad'; ?>">Contabilidad</a>
                                            </li>
                                            <li>
                                                <a href="<?php echo BASE_URL.'erp/cargarContenido/bancos'; ?>">Bancos</a>
                                            </li>
                                            <li>
                                                Ctas. por cobrar
                                            </li>
                                            <li>
                                                Ctas. por pagar
                                            </li>    
                                            <li>
                                                Inventarios
                                            </li> 
                                            <li>
                                                Activos fijos
                                            </li> 
                                            <li>
                                                RRHH
                                            </li> 
                                            <li>
                                                Punto de venta 
                                            </li>                                        
                                        </ul>
                                        <div class="delimitador">                                 
                                            <img class="img-md" src="<?php echo BASE_URL; ?>img/erp/mod-rrhh.jpg"  />
                                        </div>                                         
                                        <p>Información técnica: Nuestra aplicación funciona con un servidor glasfish o web logic, y con una base de datos oracle express o superiores.</p>                                    
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>  
                </div>
                <div class="col-md-4">
                    <section>                 
                        <div class="cards">
                            <div class="card dark">
                                <div class="box" >
                                    <div class="blue-text">                                     
                                        <h3>Servidores HP</h3>
                                        <div class="delimitador">                                 
                                            <a href="<?php echo BASE_URL.'servidores/cargarContenido/hp'; ?>"><img class="img-md" src="<?php echo BASE_URL; ?>img/servidores/HP ProLiant ML350 Gen9.jpg"  /></a>
                                        </div> 
                                        <h3>Servidores DELL</h3>
                                        <div class="delimitador">                                 
                                            <a href="<?php echo BASE_URL.'servidores/cargarContenido/dell'; ?>"><img class="img-md" src="<?php echo BASE_URL; ?>img/servidores/servidor-dell.jpg"  /></a>
                                        </div>                                         
                                    </div>
                                    <p>Ideal para proyectos, PYMES y multinacionales.</p>
                                </div>
                            </div>
                        </div> 
                    </section>                     
                </div>
                <div class="col-md-4">
                    <section>                 
                        <div class="cards">
                            <div class="card dark">
                                <div class="box" >
                                    <div class="blue-text">
                                        <h3>Outsourcing</h3>                                       
                                        <h1>Personal IT</h1>
                                        <div class="delimitador">
                                            <a href="<?php echo BASE_URL.'outsourcing'; ?>"><img src="<?php echo BASE_URL; ?>img/solucion-rrhh.jpg"  /></a>
                                        </div>                                            
                                    </div>
                                    <p>Ideal para proyectos informáticos, IN-HOUSE, call center, BPOs.</p>
                                </div>
                            </div>
                        </div> 
                    </section>                		
                </div>
            </div>
        </div>    
        <div class="col-md-1">&nbsp;</div>        
    </div>
    <!--div class="row">  
        <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
            <table class="table table-bordered table-hover table-striped">
                <tr ng-repeat="nombreDeObjeto in miVector">
                    <td>{{nombreDeObjeto.name}}</td>
                    <td>{{nombreDeObjeto.snippet}}</td>
                </tr>
            </table>
        </div>                                   
    </div-->    


