
    <div class="modal fade bs-example-modal-lg" tabindex="-1" id="contactUs" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header personalHeader">
                    <h2>Contactanos</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">x</span></button>
                </div>                
                <div class="modal-body myModalBody">                    
                    <div class="row">
                        <div class="col-md-6">   
                            <h1>Mapa</h1>
                        </div>
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-10">
                                    <form method="post" id="mensajeForm" action="./?action=send_mess">                                        
                                        <div class="form-group">
                                        <div class="form-group">
                                            <label class="control-label">Nombre:</label>
                                            <input required="required" name="nombre" id="nombre" type="text" class="form-control inputT" ng-model="nuevoMensaje.correo"/>
                                        </div>										
                                            <label class="control-label">Correo:</label>
                                            <input required="required" name="correo" id="correo" type="text" class="form-control inputT" ng-model="nuevoMensaje.correo"/>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Asunto:</label>
                                            <input required="required" name="asunto" id="asunto" type="text" class="form-control inputT" ng-model="nuevoMensaje.correo"/>
                                        </div>										
                                        <div class="form-group">
                                            <label class="control-label">Mensaje:</label>
                                            <textarea required="required" class="form-control" name="msg" id="texto" rows="5" placeholder="Contáctanos, escribe aquí tu mensaje."></textarea>
                                        </div>
                                        <div class="g-recaptcha" data-sitekey="6Lc03QQTAAAAAJ2bgugZAsttK4BbLDTP3sk9jjNS"></div>
                                        <p id="info">Gracias por contactarnos. Pronto nos estaremos comunicando contigo.</p>
                                        <button class="btn btn-primary"  type="submit">Enviar</button>
                                    </form>
                                </div>
                                <div class="col-md-2"  ></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer myModalFooter">                                            
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">  
        <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
            <h2>SSISA en Vista index</h2> 
        </div>                                   
    </div>
    <div class="row">
            <div class="col-md-3 centrado">
                    <div class="list-group">
                      <a href="#" class="list-group-item active">
                            Acerca de SSISA
                      </a>
                      <a href="#" class="list-group-item" ng-click="mostrarMensaje()">Contactanos</a>                      
                      <a href="#" class="list-group-item" ng-click="getERP()">Quienes Somos</a>
                      <a href="#" class="list-group-item">Portafolio</a>
                      <a href="<?php echo BASE_URL.'erp'; ?>" class="list-group-item">ERP</a>
                      <a href="<?php echo BASE_URL.'cotizared'; ?> " class="list-group-item">Cotiza tu red</a>
                      <a href="<?php echo BASE_URL.'cotizaweb'; ?> " class="list-group-item">Cotización tu página Web</a>                    
                      <a href="#" class="list-group-item" onclick="$('#contactUs').modal();">Contactanos</a>			  
                    </div>
            </div>
            <div class="col-md-3">
		<section>
                    <div class="cards">
                        <div class="card">
                            <div class="box" >
                                <div class="blue-text">
                                    <h3>Solución ERP </h3>
                                    <ul>
                                        <li>
                                            Contabilidad
                                        </li>
                                        <li>
                                            Bancos
                                        </li>
                                        <li>
                                            Cuentas por cobrar
                                        </li>
                                        <li>
                                            Cuentas por pagar
                                        </li>    
                                        <li>
                                            Inventarios
                                        </li> 
                                        <li>
                                            Activos fijos
                                        </li> 
                                        <li>
                                            Recursos humanos
                                        </li> 
                                        <li>
                                            Punto de venta 
                                        </li>                                        
                                    </ul>
                                    <p>Información técnica: Nuestra aplicación funciona con un servidor glasfish o web logic, y con una base de datos oracle express o superiores.</p>                                    
                                </div>
                                
                            </div>
                        </div>
                    </div>
		</section>  
            </div>
            <div class="col-md-3">
		<section>                 
                    <div class="cards">
                        <div class="card dark">
                            <div class="box" >
                                <div class="blue-text">
                                    <h1>Renta y Venta</h1>                                       
                                    <h3>Equipos y Suministros</h3>
                                    <div class="delimitador">                                 
                                        <img src="img/renta-equipo.jpg"  />
                                    </div>                                            
                                </div>
                                <p>Ideal para proyectos, conferencias, eventos, PYMES y multinacionales.</p>
                            </div>
                        </div>
                    </div> 
		</section>                     
            </div>
            <div class="col-md-3">
		<section>                 
                    <div class="cards">
                        <div class="card dark">
                            <div class="box" >
                                <div class="blue-text">
                                    <h3>Outsourcing</h3>                                       
                                    <h1>Personal IT</h1>
                                    <div class="delimitador">
                                        <img src="img/solucion-rrhh.jpg"  />
                                    </div>                                            
                                </div>
                                <p>Ideal para proyectos informáticos, IN-HOUSE, call center, BPOs.</p>
                            </div>
                        </div>
                    </div> 
		</section>                		
            </div>		
    </div>
    <div class="row">  
        <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
            <table class="table table-bordered table-hover table-striped">
                <tr ng-repeat="nombreDeObjeto in miVector">
                    <td>{{nombreDeObjeto.name}}</td>
                    <td>{{nombreDeObjeto.snippet}}</td>
                </tr>
            </table>
        </div>                                   
    </div>    


