<div class="row">
    <div class="col-md-3 col-lg-3">&nbsp;</div>
        <div class="col-md-6 col-lg-6">
            <h2>Desarrollo a la Medida</h2>
            
            <h4>¿Por qué utilizar el desarrollo a la medida?</h4>
            <p>                
                Cada empresa cuenta con necesidades, intereses y problemas diferentes. Dichas diferencias poseen su génesis en las características y particularidades de sus negocios, y en definitiva de la realidad del mercado del cual forman parte.
                En SSISA creemos en la calidad concebida como la satisfacción de las necesidades de Nuestros clientes , es por ello que nuestro servicio de desarrollo de aplicaciones se centra en crear soluciones de calidad, que satisfagan las necesidades particulares de cada cliente, su mercado y su estrategia de negocios.
                ¿Qué es un desarrollo a medida?
                Un desarrollo a medida consiste en la elaboración de un producto de software basado en las especificaciones particulares del cliente. De esta manera el producto se adapta a las necesidades del cliente y no al revés como suele suceder con la adquisición de paquetes de software comerciales. Para ello se requiere una clara identificación las necesidades del cliente y su correspondiente traducción en especificaciones de software.
                Para la creación de un Desarrollo a Medida, es necesaria la definición de un Proyecto que arroje como resultado el producto de software con las características identificadas.
            </p>
            <h2>Herramientas en que utilizamos:</h2>
            <ol>
                <li>Jdeveloper,</li>
                <li>C#, .NET,</li>
                <li>HTML, PHP,</li>
                <li>Bases de datos: Oracle, SQL Server, MYSQL, …,</li>
                <li>Sistemas operativos: Windows, Linux, IOS MAC, Android, …</li>
                <li>Weblogic y Glassfish,</li>
                <li>Developer Forms,</li>
                <li>MQ Series,</li>
                <li>Sockets,</li>
                <li>Web services.</li>
            </ol>
        </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>

