<div class="row">
    <div class="col-md-3 col-lg-3">
        <?php include_once ROOT .'views' . DS . 'layout' . DS . DEFAULT_LAYOUT . DS . 'left_column.php'; ?>
    </div>
    <div class="col-md-6 col-lg-6">
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <div class="col-md-9 col-lg-9">
                    <h2>Sistema para recargas a teléfonos móviles</h2>
                    <p>
                        Nuestro Sistema de Recargas ofrece a las empresas que cuentan con muchas sucursales y/o alto tráfico de personas en sus locaciones, el servicio de venta de recargas de telefonía celular de TIGO, CLARO Y MOVISTAR sin necesidad de utilizar un teléfono celular.
                    </p>
                    <p>Nuestra solución cuenta con las siguientes características:</p>                    
                    <ol>
                        <li>Recarga de celular a cualquier usuario de cualquier empresa de telecomunicaciones,</li>
                        <li>Pago en línea de recargas a cuenta bancaria,</li>
                        <li>Solicitud en Línea de recargas,</li>
                        <li>Saldo inmediato,</li>
                        <li>Reportes diarios y semanales</li>
                        <li>Seguridad Individual</li>
                    </ol>                    
                </div>
                <div class="col-md-3 col-lg-3">&nbsp;</div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <?php if(isset($this->msg)){echo $this->msg;}?>                
                <button onclick="$('#contizar').modal();" class="btn btn-success">Solicitar cotización</button>                    
            </div>
        </div>        
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <div class="delimitador">
                        <img src="<?php echo BASE_URL; ?>img/logo-claro.jpg"  />
                    </div> 
                </div>
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <div class="delimitador">
                        <img src="<?php echo BASE_URL; ?>img/logo-movistar.jpg"  />
                    </div> 
                </div>
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <div class="delimitador">
                        <img src="<?php echo BASE_URL; ?>img/logo-tigo.png"  />
                    </div> 
                </div>                
            </div>
        </div> 
    </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>
<div class="modal fade bs-example-modal-lg" tabindex="-1" id="contizar" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Solicitar cotización de sistema de recargas en línea</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>                        
            </div>                
            <div class="modal-body"> 
        <div class="row">
            <div class="col-md-6 col-lg-6">              
                <form action="<?php echo BASE_URL.'sistemarecargas/cotizar'; ?>" method="post" id="formCotizar">
                    <div class="form-group">
                        <label for="inputEmail">e-mail</label>
                        <input type="email" class="form-control" name="Email" placeholder="e-mail">
                    </div>
                    <div class="form-group">
                        <label for="Empresa">Nombre / Empresa</label>
                        <input type="text" class="form-control" name="Nombre" placeholder="Ingrese un nombre">
                    </div>
                    <div class="form-group">
                        <label for="InputTel">Teléfono</label>
                        <input type="text" class="form-control" name="Telefono" placeholder="Ingrese su teléfono">
                    </div>
                    <div class="form-group">
                        <label for="InputDir">Dirección</label>
                        <input type="text" class="form-control" name="Direccion" placeholder="Ingrese su dirección">
                    </div>                     
                    <div class="g-recaptcha" data-sitekey="6LcOTgwTAAAAANzXJ8XcyGl05oEQ5A7xv1Go6T4Z"></div>
                    <button onclick="validarDatos();" class="btn btn-primary">Cotizar</button>
                </form>  
            </div>
            <div class="col-md-6 col-lg-6">&nbsp;</div>
        </div>                         
            </div>                    
            <div class="modal-footer myModalFooter">                                            
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
<script>
    function validarDatos(){
        $("#formCotizar").validate({
                rules: {
                        Email: { required:true, email: true},
                        Nombre: { required: true},                           
                        Telefono: { required:true, number:true},
                        Direccion: { required:true}                         
                },
                messages: {
                        Email: "Este campo debe tener formato de correo y es necesario.",
                        Nombre : "El campo nombre es necesario",                          
                        Telefono : "Este campo debe tener formato numérico y es necesario.",
                        Direccion : "El campo dirección es necesario",                        
                }
        });
        if($("#formCotizar").valid())
        { 
            $('#formCotizar').submit();
        }       
    }
</script>
