<div class="row">
    <div class="col-md-3 col-lg-3">&nbsp;</div>
    <div class="col-md-6 col-lg-6">
        <div class="row">
            <div class="col-md-6 col-lg-6">
                <h2>Recarga en Línea</h2>
                <?php if(isset($this->msg)){echo $this->msg;}?>                
                <form action="<?php echo BASE_URL.'sistemarecargas/cotizar'; ?>" method="post">
                    <div class="form-group">
                        <label for="inputEmail1">e-mail</label>
                        <input type="email" class="form-control" name="Email" placeholder="e-mail">
                    </div>
                    <div class="form-group">
                        <label for="Empresa">Nombre / Empresa</label>
                        <input type="text" class="form-control" name="Nombre" placeholder="Ingrese un nombre">
                    </div>                                                  
                    <button type="submit" class="btn btn-primary">Cotizar</button>
                </form>  
            </div>
            <div class="col-md-6 col-lg-6">&nbsp;</div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <div class="col-md-9 col-lg-9">
                    <h2>Sistema para recargas a teléfonos móviles</h2>
                    <p>
                        Nuestro Sistema de Recargas ofrece a las empresas que cuentan con muchas sucursales y/o alto tráfico de personas en sus locaciones, el servicio de venta de recargas de telefonía celular de TIGO, CLARO Y MOVISTAR sin necesidad de utilizar un teléfono celular.
                    </p>
                    <p>Nuestra solución cuenta con las siguientes características:</p>                    
                    <ol>
                        <li>Recarga de celular a cualquier usuario de cualquier empresa de telecomunicaciones,</li>
                        <li>Pago en línea de recargas a cuenta bancaria,</li>
                        <li>Solicitud en Línea de recargas,</li>
                        <li>Saldo inmediato,</li>
                        <li>Reportes diarios y semanales</li>
                        <li>Seguridad Individual</li>
                    </ol>                    
                </div>
                <div class="col-md-3 col-lg-3">&nbsp;</div>
            </div>
        </div>   
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <div class="delimitador">
                        <img src="<?php echo BASE_URL; ?>img/logo-claro.jpg"  />
                    </div> 
                </div>
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <div class="delimitador">
                        <img src="<?php echo BASE_URL; ?>img/logo-movistar.jpg"  />
                    </div> 
                </div>
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <div class="delimitador">
                        <img src="<?php echo BASE_URL; ?>img/logo-tigo.png"  />
                    </div> 
                </div>                
            </div>
        </div> 
    </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>
