<div class="row">
    <div class="col-md-4">&nbsp;</div>
        <div class="col-md-4">
            <h2>COTIZA TU INSTALACION ELÉCTRICA</h2>
            <form>
                <div class="form-group">
                    <label for="inputEmail1">e-mail</label>
                    <input type="email" class="form-control" name="Email" placeholder="e-mail">
                </div>
                <div class="form-group">
                    <label for="Empresa">Nombre / Empresa</label>
                    <input type="text" class="form-control" name="Nombre" placeholder="Ingrese un nombre">
                </div>                
                <div class="form-group">
                    <label for="InputPaginas">Número de puntos de conección</label>
                    <input type="text" class="form-control" name="noPuntos" placeholder="Ingrese un número">
                </div>                                            
                
                <button type="submit" class="btn btn-primary">Cotizar</button>   
                
                <div class="delimitador">
                    <img class="centrado"  src="img/instalaciones-electricas.jpg"  />
                </div>
            </form>            
        </div>
    <div class="col-md-4">&nbsp;</div>
</div>

