<div class="row">
    <div class="col-md-4">&nbsp;</div>
        <div class="col-md-4">
            <h2>COTIZA TU PAGINA</h2>
            <?php if(isset($this->msg)){echo $this->msg;}?>
            <form action="<?php echo BASE_URL.'cotizaweb/cotizar'; ?>" method="post">
                <div class="form-group">
                    <label for="inputEmail">e-mail</label>
                    <input type="email" class="form-control" name="Email" placeholder="e-mail">
                </div>
                <div class="form-group">
                    <label for="Empresa">Nombre / Empresa</label>
                    <input type="text" class="form-control" name="Nombre" placeholder="Ingrese un nombre">
                </div>                
                <div class="form-group">
                    <label for="InputPaginas">Número de paginas</label>
                    <input type="text" class="form-control" name="noPaginas" placeholder="Ingrese un número">
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="responsive" value="1"> Responsive
                    </label>
                </div>
                <div class="delimitador">
                    <img class="centrado"  src="<?php echo BASE_URL; ?>img/responsive-website.jpg"  />
                </div>                                    
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="estatica" value="1"> Estática / Dinamica
                    </label>
                </div>       
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="animada" value="1"> Efectos de animación
                    </label>
                </div>                 
                <button type="submit" class="btn btn-primary">Cotizar</button>
            </form>            
        </div>
    <div class="col-md-4">&nbsp;</div>
</div>