<div class="row">
    <div class="col-md-4">&nbsp;</div>
        <div class="col-md-4">
            <h2>COTIZA TU PAGINA</h2>
            <form>
                <div class="form-group">
                    <label for="inputEmail1">e-mail</label>
                    <input type="email" class="form-control" name="Email" placeholder="e-mail">
                </div>
                <div class="form-group">
                    <label for="Empresa">Nombre / Empresa</label>
                    <input type="text" class="form-control" name="Nombre" placeholder="Ingrese un nombre">
                </div>                
                <div class="form-group">
                    <label for="InputPaginas">Número de paginas</label>
                    <input type="text" class="form-control" name="noPaginas" placeholder="Ingrese un número">
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox"> Responsive
                    </label>
                </div>
                <div class="delimitador">
                    <img class="centrado"  src="img/responsive-website.jpg"  />
                </div>                                    
                <div class="checkbox">
                    <label>
                        <input type="checkbox"> Estática / Dinamica
                    </label>
                </div>       
                <div class="checkbox">
                    <label>
                        <input type="checkbox"> Efectos de animación
                    </label>
                </div>                 
                <button type="submit" class="btn btn-primary">Enviar</button>
            </form>            
            <p><?php print_r($this->posts); ?></p>
        </div>
    <div class="col-md-4">&nbsp;</div>
</div>