<div class="row">
    <div class="col-md-3 col-lg-3">&nbsp;</div>
    <div class="col-md-6 col-lg-6">
        <div class="row">
            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <h3>COTIZAR IMPLEMENTACION DE PLATAFORMA PARA E-LEARNING</h3>  
                </div>
            </div>     
            <div class="col-md-6 col-lg-6 blue-text">
                <h3>Herramientas que ofrecemos:</h3>
                <ul> 
                    <li>Dominio y hosting</li>
                    <li>Instalación y Configuración</li>
                    <li>Capacitación</li>
                    <li>Plataforma Moodle u otros</li>
                </ul>                
            </div>            
            <div class="col-md-6 col-lg-6">
                <?php if(isset($this->msg)){echo $this->msg;}?>
                <form action="<?php echo BASE_URL.'elearning/cotizar'; ?>" method="post">
                    <div class="form-group">
                        <label for="inputEmail">e-mail</label>
                        <input type="email" class="form-control" name="Email" placeholder="e-mail">
                    </div>
                    <div class="form-group">
                        <label for="Nombre">Nombre / Empresa</label>
                        <input type="text" class="form-control" name="Nombre" placeholder="Ingrese un nombre">
                    </div>
                    <div class="form-group">
                        <label for="Motivo">¿Para que deseas utilizar el servicio de e-learning?</label>
                        <input type="text" class="form-control" name="Motivo" placeholder="Ingrese un nombre">
                    </div>                      
                    <button type="submit" class="btn btn-primary">Cotizar</button>
                </form>        
            </div>
        </div>        
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <div class="col-md-9 col-lg-9">
                    <h2>¿Que es e-Learning?</h2>
                    <p>
                        Es un aprendizaje que se apoya en medios electrónicos para su realización, sin importar la modalidad a distancia o presencial en que se contextualiza. Generalmente, es el aprendizaje basado o apoyado en tecnologías de redes como complemento del aprendizaje presencial, donde es posible incluir ejercicios de simulación, participar de discusiones grupales, enlaces de sitios de Internet, trabajos colaborativos, etc.  (Según Fainholc, 2008)                      
                    </p>                   
                </div>
                <div class="col-md-3 col-lg-3">&nbsp;</div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <div class="col-md-9 col-lg-9">
                    <h2>¿Qué es una plataforma de e-Learning?</h2>
                    <p>
                        La plataforma de e-learning, es un espacio virtual de aprendizaje orientado a facilitar la experiencia de capacitación a distancia, tanto para empresas como para instituciones educativas.     
                        Este sistema permite la creación de "aulas virtuales", interacción entre tutores y alumnos, realización de evaluaciones, el intercambio de archivos, la participación en foros, chats, etc.
                    </p>                    
                </div>
                <div class="col-md-3 col-lg-3">&nbsp;</div>
            </div>
        </div>        
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">&nbsp;</div>   
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <div class="delimitador">
                        <img src="<?php echo BASE_URL; ?>img/elearning.jpg"  />
                    </div> 
                </div> 
            </div>
        </div> 
    </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>