<div class="row">
    <div class="col-md-3 col-lg-3">
        <?php include_once ROOT .'views' . DS . 'layout' . DS . DEFAULT_LAYOUT . DS . 'left_column.php'; ?>
    </div>
    <div class="col-md-6 col-lg-6">
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <div class="col-md-9 col-lg-9">
                    <h2>¿Que es hosting?</h2>
                    <p>
                        Es el servicio que provee a los usuarios de Internet un sistema para poder almacenar información, imágenes, vídeo, o cualquier contenido accesible vía web. En este caso hosting se refiere al lugar que ocupa una página web, sitio web, sistema, correo electrónico, archivos etc. en un servidor que por lo general hospeda varias aplicaciones o páginas web.
                    </p>  
                </div>
                <div class="col-md-3 col-lg-3">&nbsp;</div>
            </div>
        </div>       
        <div class="row">
            <div class="col-md-6 col-lg-6 blue-border">
                <h3>Solicitar cotización de hosting</h3>
                <?php if(isset($this->msg)){echo $this->msg;}?>                
                <form action="<?php echo BASE_URL.'hosting/cotizar'; ?>" method="post" id="formCotizar">
                    <div class="form-group">
                        <label for="inputEmail">e-mail</label>
                        <input type="email" class="form-control" name="Email" placeholder="e-mail">
                    </div>
                    <div class="form-group">
                        <label for="Empresa">Nombre / Empresa</label>
                        <input type="text" class="form-control" name="Nombre" placeholder="Ingrese un nombre">
                    </div>
                    <div class="form-group">
                        <label for="InputTel">Teléfono</label>
                        <input type="text" class="form-control" name="Telefono" placeholder="Ingrese su teléfono">
                    </div>
                    <div class="form-group">
                        <label for="InputDir">Dirección</label>
                        <input type="text" class="form-control" name="Direccion" placeholder="Ingrese su dirección">
                    </div>                     
                    <div class="g-recaptcha" data-sitekey="6LcOTgwTAAAAANzXJ8XcyGl05oEQ5A7xv1Go6T4Z"></div>
                    <button onclick="validarDatos();" class="btn btn-primary">Cotizar</button>
                </form>    
            </div>
            <div class="col-md-6 col-lg-6">&nbsp;</div>
        </div>
    </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>
<div class="modal fade bs-example-modal-lg" tabindex="-1" id="contizar" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Solicitud de cotización</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>                        
            </div>                
            <div class="modal-body"> 
                          
            </div>                    
            <div class="modal-footer myModalFooter">                                            
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
<script>
    function validarDatos(){
        $("#formCotizar").validate({
                rules: {
                        Email: { required:true, email: true},
                        Nombre: { required: true},                           
                        Telefono: { required:true, number:true},
                        Direccion: { required:true}                         
                },
                messages: {
                        Email: "Este campo debe tener formato de correo y es necesario.",
                        Nombre : "El campo nombre es necesario",                          
                        Telefono : "Este campo debe tener formato numérico y es necesario.",
                        Direccion : "El campo dirección es necesario",                        
                }
        });
        if($("#formCotizar").valid())
        { 
            $('#formCotizar').submit();
        }       
    }
</script>

