<div class="row">
    <div class="col-md-3 col-lg-3">
        <?php include_once ROOT .'views' . DS . 'layout' . DS . DEFAULT_LAYOUT . DS . 'left_column.php'; ?>
    </div>
    <div class="col-md-6 col-lg-6 be-white">
        <div class="row">
            <div class="col-md-6 col-lg-6">
                <h2>Servidores DELL</h2>
            </div>
        </div>
        <div class="row" style="margin: 30px;">
            <form action="<?php echo BASE_URL.'servidores/prepararSolicitud/DellPowerEdgeT20'; ?>" method="post">
                <div class="col-md-12 col-lg-12">
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="delimitador">
                                <img src="<?php echo BASE_URL; ?>img/servidores/Dell PowerEdge T20.jpg"  />
                        </div> 
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <h3>Dell PowerEdge T20</h3>                        
                        <p>       
                            Dell PowerEdge T20, Intel 3.2 GHz Xeon E3-1225V3, 4 GB RAM, 1 TB Capacidad del disco duro, Sin sistema operativo
                        </p>
                        <p>
                            El servidor PowerEdge T20 incluye gran capacidad de almacenamiento interno y rendimiento con capacidad en un chasis en mini torre silencioso diseñado para brindar un funcionamiento eficiente y sin preocupaciones. Con el T20, los datos y las aplicaciones de varias computadoras de escritorio y workstations se pueden consolidar en un solo servidor para impulsar la colaboración y la productividad.
                        </p>
                        <p>
                            <strong>Protección de datos:</strong> protéjase de la pérdida de datos con compatibilidad incorporada para la duplicación de archivos con un arreglo redundante basado en software de discos independientes (RAID). La memoria de código de corrección de errores (ECC) agrega un nivel adicional para la protección de datos.
                        </p>
                        <p>
                            <strong>Respaldo y restauración:</strong> agregue las funciones de respaldo y restauración automáticas con el conjunto de colaboración completo, Microsoft Windows Small Business Server.
                        </p>
                        <p>
                            <strong>Fácil administración:</strong> actualice aplicaciones de software en un solo lugar, en lugar de en varias computadoras para simplificar las tareas y ahorrar tiempo. 
                        </p>
                        <button type="submit" class="btn btn-primary">Solicitar cotización</button> 
                    </div>
                </div>
            </form>                     
        </div>           
    </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>