<div class="row">
    <div class="col-md-3 col-lg-3">
        <?php include_once ROOT .'views' . DS . 'layout' . DS . DEFAULT_LAYOUT . DS . 'left_column.php'; ?>
    </div>
    <div class="col-md-6 col-lg-6">
        <div class="row">
            <div class="col-md-6 col-lg-6">
                <h2>Servidores HP</h2>
            </div>
        <div class="row" style="margin: 30px;">
            <form action="<?php echo BASE_URL.'servidores/prepararSolicitud/HPProLiantDL360Gen9'; ?>" method="post">
                <div class="col-md-12 col-lg-12">
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="delimitador">
                                <img src="<?php echo BASE_URL; ?>img/servidores/HP ProLiant DL360 Gen9.jpg"  />
                        </div> 
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <h3>HP ProLiant DL360 Gen9</h3>                        
                        <p>
                            Intel Xeon E5-2630v3 8-Core (2.40GHz 20MB) 16GB RAM (1 x 16GB), 8 Bahías Hot Plug 2.5in SFF SC, Smart Array P440ar/2G with Megacell, No incluye DVD-RW
                        </p>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="HP_ProLiant_ML350" value="1"> Agregar a cotización 
                            </label>
                        </div>
                        <button type="submit" class="btn btn-primary">Solicitar cotización</button> 
                    </div>
                </div>
            </form>                     
        </div>   
        <div class="row" style="margin: 30px;">
            <form action="<?php echo BASE_URL.'servidores/prepararSolicitud/HPProLiantML350Gen9'; ?>" method="post">                
                <div class="col-md-12 col-lg-12">
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="delimitador">
                            <img src="<?php echo BASE_URL; ?>img/servidores/HP ProLiant ML350 Gen9.jpg"  />
                        </div> 
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <h3>HP ProLiant ML350 Gen9</h3>                           
                        <p>
                            Intel Xeon E5-2620v3 6 Core (2.4 GHz 15MB L3 Caché ), 16GB RAM,8 Bahías HDD Hot Plug 2.5" SFF SC, Smart Array.  No incluye DVD-RW
                        </p>
                        <p>
                            El servidor HP ProLiant DL360 Gen9 dispone de hasta 24 ranuras DIMM HP DDR4 SmartMemory con una memoria máxima de hasta 1,5 TB, con inteligencia integrada para mejorar el rendimiento, reducir el tiempo de inactividad y los costes de energía, mejorando el rendimiento hasta en un 14 %.
                        </p>
                        <p>
                            Tiene la opción de adaptadores incorporados 4x1 GbE, HP FlexibleLOM o PCle vertical de 1 GbE a 40 GbE, lo que le proporciona flexibilidad de ancho de banda de red y de estructura para que pueda adaptarse y crecer según las necesidades empresariales cambiantes.
                        </p>                        
                        <div class="checkbox">
                            <label>
                              <input type="checkbox" name="HP_ProLiant_ML350" value="1"> Agregar a cotización
                            </label>
                        </div>
                        <button type="submit" class="btn btn-primary">Solicitar cotización</button> 
                    </div>
                </div>
            </form>                     
        </div> 
        <div class="row" style="margin: 30px;">
            <form action="<?php echo BASE_URL.'servidores/prepararSolicitud/HPProLiantML110Gen9'; ?>" method="post">
                <div class="col-md-12 col-lg-12">
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="delimitador">
                            <img src="<?php echo BASE_URL; ?>img/servidores/HP ProLiant ML110 Gen9.png"  />
                        </div> 
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <h3>HP ProLiant ML110 Gen9</h3>                         
                        <p>
                            Intel Xeon E5-2603v3 6-Core (1.60GHz 15MB) 8GB RAM DDR4 2133MHz RDIMM, 1 HDD 2TB (7.2k rpm) Non-Hot Plug 3.5in SATA, Dynamic Smart Array B140i, DVD-RW,  550W 
                        </p>
                        <div class="checkbox">
                            <label>
                              <input type="checkbox" name="HP_ProLiant_ML110" value="1"> Agregar a cotización
                            </label>
                        </div> 
                        <button type="submit" class="btn btn-primary">Solicitar cotización</button>                         
                    </div>                 
                </div>
            </form>                     
        </div>         
    </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>
   
