<div class="row">
    <div class="col-md-3 col-lg-3">
        <?php include_once ROOT .'views' . DS . 'layout' . DS . DEFAULT_LAYOUT . DS . 'left_column.php'; ?>
    </div>
    <div class="col-md-6 col-lg-6">
        <div class="row">
            <div class="col-md-6 col-lg-6">
                <h2>Servidores HP</h2>
            </div>
        <div class="row" style="margin: 30px;">
            <form action="<?php echo BASE_URL.'servidores/prepararSolicitud/HP ProLiant DL360 Gen9/Intel Xeon E5-2630v3 8-Core (2.40GHz 20MB)/16GB RAM/80tb'; ?>" method="post">
                <div class="col-md-12 col-lg-12">
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="delimitador">
                                <img src="<?php echo BASE_URL; ?>img/servidores/HP ProLiant DL360 Gen9.jpg"  />
                        </div> 
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <h3>HP ProLiant DL360 Gen9</h3>                        
                        <p>
                            Intel Xeon E5-2630v3 8-Core (2.40GHz 20MB) 16GB RAM (1 x 16GB), 8 Bahías Hot Plug 2.5in SFF SC, Smart Array P440ar/2G with Megacell, No incluye DVD-RW
                        </p>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="HP_ProLiant_ML350" value="1"> Agregar a cotización 
                            </label>
                        </div>
                        <button type="submit" class="btn btn-primary">Solicitar cotización</button> 
                    </div>
                </div>
            </form>                     
        </div>   
        <div class="row" style="margin: 30px;">
            <form action="<?php echo BASE_URL.'servidores/prepararSolicitud/HP ProLiant ML350 Gen9'; ?>" method="post">                
                <div class="col-md-12 col-lg-12">
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="delimitador">
                            <img src="<?php echo BASE_URL; ?>img/servidores/HP ProLiant ML350 Gen9.jpg"  />
                        </div> 
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <h3>HP ProLiant ML350 Gen9</h3>                           
                        <p>
                            Intel Xeon E5-2620v3 6 Core (2.4 GHz 15MB L3 Caché ), 16GB RAM,8 Bahías HDD Hot Plug 2.5" SFF SC, Smart Array.  No incluye DVD-RW
                        </p>
                        <div class="checkbox">
                            <label>
                              <input type="checkbox" name="HP_ProLiant_ML350" value="1"> Agregar a cotización
                            </label>
                        </div>
                        <button type="submit" class="btn btn-primary">Solicitar cotización</button> 
                    </div>
                </div>
            </form>                     
        </div> 
        <div class="row" style="margin: 30px;">
            <form action="<?php echo BASE_URL.'servidores/prepararSolicitud/HP ProLiant ML110 Gen9'; ?>" method="post">
                <div class="col-md-12 col-lg-12">
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="delimitador">
                            <img src="<?php echo BASE_URL; ?>img/servidores/HP ProLiant ML110 Gen9.png"  />
                        </div> 
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <h3>HP ProLiant ML110 Gen9</h3>                         
                        <p>
                            Intel Xeon E5-2603v3 6-Core (1.60GHz 15MB) 8GB RAM DDR4 2133MHz RDIMM, 1 HDD 2TB (7.2k rpm) Non-Hot Plug 3.5in SATA, Dynamic Smart Array B140i, DVD-RW,  550W 
                        </p>
                        <div class="checkbox">
                            <label>
                              <input type="checkbox" name="HP_ProLiant_ML110" value="1"> Agregar a cotización
                            </label>
                        </div> 
                        <button type="submit" class="btn btn-primary">Solicitar cotización</button>                         
                    </div>                 
                </div>
            </form>                     
        </div>         
    </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>
   
