<div class="row">
    <div class="col-md-4 col-lg-4">&nbsp;</div>
        <div class="col-md-4 col-lg-4">
            <h2>Cotizar outsourcing personal y planilla</h2>
            <?php if(isset($this->msg)){echo $this->msg;}?>
            <form action="<?php echo BASE_URL.'outsourcing/cotizar'; ?>" method="post">
                <div class="form-group">
                    <label for="inputEmail1">e-mail</label>
                    <input type="email" class="form-control" name="Email" placeholder="Ingrese su e-mail">
                </div>
                <div class="form-group">
                    <label for="Empresa">Nombre / Empresa</label>
                    <input type="text" class="form-control" name="Nombre" placeholder="Ingrese un nombre">
                </div>                
                <div class="form-group">
                    <label for="InputPuesto">Puesto a cotizar:</label>
                    <input type="text" class="form-control" name="Puesto" placeholder="Ingrese puesto que desea cotizar">
                </div>                                            
                <div class="form-group">
                    <label for="InputHerramienta">Herramienta a utilizar:</label>
                    <input type="text" class="form-control" name="Herramienta" placeholder="Ingrese la herramienta a usar">
                </div>
                <div class="form-group">
                    <label for="InputLugar">Ubicación de la empresa:</label>
                    <input type="text" class="form-control" name="Lugar" placeholder="Ingrese un lugar">
                </div>
                <div class="form-group">
                    <label for="InputTiempo">Tiempo a trabajar:</label>
                    <input type="text" class="form-control" name="Tiempo" placeholder="Ingrese el tiempo a contratar">
                </div>                   
                <button type="submit" class="btn btn-primary">Cotizar</button> 
            </form>                
            
            <h4>¿Por qué utilizar el outsourcing de personal?</h4>
            <p>                
                El contar con una empresa encargada de realizar una de las labores no estratégicas de nuestro negocio representa ventajas en el área específica cuyas labores estamos delegando.
            </p>
            <p>                
               En SSISA ofrecemos la búsqueda de posiciones de alta gerencia, gerencia media, profesional y técnica de apoyo en el área de IT (Informática, tecnología, computación y telecomunicaciones). Contamos con sistemas de evaluaciones acorde a los perfiles de puestos de trabajo y de esta forma determinar sus competencias, habilidades y potencial de los candidatos que aplican en procesos de selección, tanto individuales, grupales y/o procesos masivos.
            </p>
            <p>                
               Si requiere contratar personal para su departamento de sistemas le ofrecemos el servicio más profesional en reclutamiento especializado para TI, con el cual usted recibe:
            </p>
            <ul style="margin-left: 40px; list-style-type: circle;">
                <li>Evaluación de funciones del puesto.</li>
                <li>Desarrollo de perfil profesional del puesto.</li>
                <li>Formación de anuncio de reclutamiento para medios electrónicos e impresos.</li>
                <li>Preselección de candidatos mediante evaluación de currículos.</li>
                <li>Sesión de entrevista de para valoración del perfil de candidatos seleccionados.</li>
                <li>Evaluación de conocimientos técnicos por escrito o práctica de cada candidato.</li>
            </ul>
            <p>Este servicio concluye cuando usted recibe el reporte de evaluación de todos los candidatos entrevistados y los mejores calificados para ser entrevistados por usted o su departamento de recursos humanos.</p>            
            <p>SSISA también le brinda el servicio de outsourcing de planilla, en la cual le llevamos la base de datos de su personal y nos encargamos del pago de la planilla respectiva.</p>
        </div>
    <div class="col-md-4 col-lg-4">&nbsp;</div>
</div>

