<div class="row">
    <div class="col-md-3 col-lg-3">
        <?php include_once ROOT .'views' . DS . 'layout' . DS . DEFAULT_LAYOUT . DS . 'left_column.php'; ?>
    </div>
    <div class="col-md-6 col-lg-6 be-white">
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <div class="col-md-9 col-lg-9">
                <h2>¿Por qué utilizar el outsourcing de personal?</h2>
                <p>                
                    El contar con una empresa encargada de realizar una de las labores no estratégicas de nuestro negocio representa ventajas en el área específica cuyas labores estamos delegando.
                </p>
                <p>                
                   En SSISA ofrecemos la búsqueda de posiciones de alta gerencia, gerencia media, profesional y técnica de apoyo en el área de IT (Informática, tecnología, computación y telecomunicaciones). Contamos con sistemas de evaluaciones acorde a los perfiles de puestos de trabajo y de esta forma determinar sus competencias, habilidades y potencial de los candidatos que aplican en procesos de selección, tanto individuales, grupales y/o procesos masivos.
                </p>
                <p>                
                   Si requiere contratar personal para su departamento de sistemas le ofrecemos el servicio más profesional en reclutamiento especializado para TI, con el cual usted recibe:
                </p>
                <ul style="margin-left: 40px; list-style-type: circle;">
                    <li>Evaluación de funciones del puesto.</li>
                    <li>Desarrollo de perfil profesional del puesto.</li>
                    <li>Formación de anuncio de reclutamiento para medios electrónicos e impresos.</li>
                    <li>Preselección de candidatos mediante evaluación de currículos.</li>
                    <li>Sesión de entrevista de para valoración del perfil de candidatos seleccionados.</li>
                    <li>Evaluación de conocimientos técnicos por escrito o práctica de cada candidato.</li>
                </ul>
                <p>Este servicio concluye cuando usted recibe el reporte de evaluación de todos los candidatos entrevistados y los mejores calificados para ser entrevistados por usted o su departamento de recursos humanos.</p>            
                <p>SSISA también le brinda el servicio de outsourcing de planilla, en la cual le llevamos la base de datos de su personal y nos encargamos del pago de la planilla respectiva.</p>       
                <form>
                    <?php if(isset($this->msg)){echo $this->msg;}?>                
                    <button onclick="$('#contizar').modal();" class="btn btn-success">Solicitar cotización</button>  
                </form>
                </div>
                <div class="col-md-3 col-lg-3">&nbsp;</div>
            </div>
        </div>       
    </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>
<div class="modal fade bs-example-modal-lg" tabindex="-1" id="contizar" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Solicitar cotización de outsourcing</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>                        
            </div>                
            <div class="modal-body"> 
        <div class="row">
            <div class="col-md-6 col-lg-6">
                <form action="<?php echo BASE_URL.'outsourcing/cotizar'; ?>" method="post" id="formCotizar">
                    <div class="form-group">
                        <label for="inputEmail">e-mail</label>
                        <input type="email" class="form-control" name="Email" placeholder="e-mail">
                    </div>
                    <div class="form-group">
                        <label for="Empresa">Nombre / Empresa</label>
                        <input type="text" class="form-control" name="Nombre" placeholder="Ingrese un nombre">
                    </div>
                    <div class="form-group">
                        <label for="InputTel">Teléfono</label>
                        <input type="text" class="form-control" name="Telefono" placeholder="Ingrese su teléfono">
                    </div>             
                    <div class="form-group">
                        <label for="InputPuesto">Puesto a cotizar</label>
                        <input type="text" class="form-control" name="Puesto" placeholder="Ingrese puesto que desea cotizar">
                    </div>                                            
                    <div class="form-group">
                        <label for="InputHerramienta">Herramienta a utilizar</label>
                        <input type="text" class="form-control" name="Herramienta" placeholder="Ingrese la herramienta a usar">
                    </div>
                    <div class="form-group">
                        <label for="InputLugar">Ubicación de la empresa</label>
                        <input type="text" class="form-control" name="Lugar" placeholder="Ingrese un lugar">
                    </div>
                    <div class="form-group">
                        <label for="InputTiempo">Tiempo a trabajar</label>
                        <input type="text" class="form-control" name="Tiempo" placeholder="Ingrese el tiempo a contratar">
                    </div>
                    <div class="g-recaptcha" data-sitekey="6LcOTgwTAAAAANzXJ8XcyGl05oEQ5A7xv1Go6T4Z"></div>
                    <button onclick="validarDatos();" class="btn btn-primary">Cotizar</button> 
                </form> 
            </div>
            <div class="col-md-6 col-lg-6">&nbsp;</div>
        </div>                          
            </div>                    
            <div class="modal-footer myModalFooter">                                            
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
<script>
    function validarDatos(){
        $("#formCotizar").validate({
                rules: {
                        Email: { required:true, email: true},
                        Nombre: { required: true},                           
                        Telefono: { required:true, number:true},
                        Lugar: { required:true}                         
                },
                messages: {
                        Email: "Este campo debe tener formato de correo y es necesario.",
                        Nombre : "El campo nombre es necesario",                          
                        Telefono : "Este campo debe tener formato numérico y es necesario.",
                        Lugar : "El campo dirección es necesario",                        
                }
        });
        if($("#formCotizar").valid())
        { 
            $('#formCotizar').submit();
        }       
    }

</script>
