<div class="row">
    <div class="col-md-3 col-lg-3">&nbsp;</div>
        <div class="col-md-6 col-lg-6">
            <h2>Outsourcing Personal y Planilla</h2>
            
            <h4>¿Por qué utilizar el outsourcing de personal?</h4>
            <p>                
                El contar con una empresa encargada de realizar una de las labores no estratégicas de nuestro negocio representa ventajas en el área específica cuyas labores estamos delegando.
            </p>
            <p>                
               En SSISA ofrecemos la búsqueda de posiciones de alta gerencia, gerencia media, profesional y técnica de apoyo en el área de IT (Informática, tecnología, computación y telecomunicaciones). Contamos con sistemas de evaluaciones acorde a los perfiles de puestos de trabajo y de esta forma determinar sus competencias, habilidades y potencial de los candidatos que aplican en procesos de selección, tanto individuales, grupales y/o procesos masivos.
            </p>
            <p>                
               Si requiere contratar personal para su departamento de sistemas le ofrecemos el servicio más profesional en reclutamiento especializado para TI, con el cual usted recibe:
            </p>
            <ul style="margin-left: 40px; list-style-type: circle;">
                <li>Evaluación de funciones del puesto.</li>
                <li>Desarrollo de perfil profesional del puesto.</li>
                <li>Formación de anuncio de reclutamiento para medios electrónicos e impresos.</li>
                <li>Preselección de candidatos mediante evaluación de currículos.</li>
                <li>Sesión de entrevista de para valoración del perfil de candidatos seleccionados.</li>
                <li>Evaluación de conocimientos técnicos por escrito o práctica de cada candidato.</li>
            </ul>
            <p>Este servicio concluye cuando usted recibe el reporte de evaluación de todos los candidatos entrevistados y los mejores calificados para ser entrevistados por usted o su departamento de recursos humanos.</p>            
            <p>SSISA también le brinda el servicio de outsourcing de planilla, en la cual le llevamos la base de datos de su personal y nos encargamos del pago de la planilla respectiva.</p>
        </div>
    <div class="col-md-3 col-lg-3">&nbsp;</div>
</div>

